### PR TITLE
luci-mod-freifunk: fix permissions for uci access

### LINKED ISSUE #23: luci-mod-freifunk: lua error accessing the "profile_expert" site and others
accessing ```/cgi-bin/luci/admin/freifunk/basics/profile_expert```  raises a lua error:

> ...r/lib/lua/luci/model/cbi/freifunk/profile_expert.lua:12: attempt to concatenate local 'community' (a boolean value)
stack traceback:
	...r/lib/lua/luci/model/cbi/freifunk/profile_expert.lua:12: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1336: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1019: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

even ```uci get feifunk.community.name``` return a valid profile-suffix (here "berlin").

This probably relates to running it on the latest OpenWrt master:
> OPENWRT_REPO=https://git.openwrt.org/openwrt/openwrt.git
OPENWRT_COMMIT=ad27c133eb606ee39fa346b7bdb26c1764ee869e
PACKAGES_PACKAGES_REPO=https://github.com/openwrt/packages.git
PACKAGES_PACKAGES_COMMIT=10fb31451e18b6a03f8070eeae373d37855ccc09
PACKAGES_LUCI_REPO=https://github.com/openwrt/luci.git
PACKAGES_LUCI_COMMIT=a573da0d191e30ccabc15b84fdc73f9b570fcf51

### PR DESCRIPTION
**Pull request by XDjackieXD**
as requested in PR #28 a pull request that adds the necessary file to fix the uci access permissions.
As I don't have the device I tested this with here with me this commit is untested so please compile the package with this branch and test if you can access the profile settings page.

### CODE REVIEW

File: modules/luci-mod-freifunk/root/usr/share/rpcd/acl.d/luci-mod-freifunk.json [hunk 1]
```diff
@@ -0,0 +1,11 @@
+{
+	"luci-mod-freifunk": {
+		"description": "Provdies access to freifunk",
+		"read": {
+			"uci": [ "freifunk", "profile_*" ],
+		},
+		"write": {
+			"uci": [ "freifunk", "profile_*" ],
```
Comment (SvenRoederer) [inline modules/luci-mod-freifunk/root/usr/share/rpcd/acl.d/luci-mod-freifunk.json:8]: I don't think, write access to the profiles_* is needed, as these files are only needed to look up some defaults.
see: https://github.com/freifunk/openwrt-packages/pull/21

**Comment by SvenRoederer** [comment]
Can you update the commit message to include a pointer to the issue fixed? Like

The LuCI-page currently fails with:

/usr/lib/lua/luci/model/cbi/freifunk/profile.lua:12: attempt to concatenate local 'community' (a boolean value)
stack traceback:
/usr/lib/lua/luci/model/cbi/freifunk/profile.lua:16: in function 'func'
/usr/lib/lua/luci/cbi.lua:66: in function 'load'
/usr/lib/lua/luci/dispatcher.lua:1348: in function '_cbi'
/usr/lib/lua/luci/dispatcher.lua:1019: in function 'dispatch'
/usr/lib/lua/luci/dispatcher.lua:980: in function 'dispatch'
/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

This is caused by returning "false" when getting the "freifunk.community.name" via luci.model.uci.
Upstream changed the luci-base package to route uci-requests through the RPCd. This change in turn requires setting up correct permissions for accessing the RPCd.

File: modules/luci-mod-freifunk/root/usr/share/rpcd/acl.d/luci-mod-freifunk.json (hunk 1 above)
Comment (XDjackieXD) [reply modules/luci-mod-freifunk/root/usr/share/rpcd/acl.d/luci-mod-freifunk.json:8]: on the other hand https://github.com/freifunk/openwrt-packages/blob/master/modules/luci-mod-freifunk/luasrc/model/cbi/freifunk/profile.lua#L25 looks a lot like it would save the profile preferences to the file names "profile_communityname" or did I miss something?

**Comment by XDjackieXD** [comment]
> Can you update the commit message to include a pointer to the issue fixed? Like

Done

File: modules/luci-mod-freifunk/root/usr/share/rpcd/acl.d/luci-mod-freifunk.json (hunk 1 above)
Comment (SvenRoederer) [reply modules/luci-mod-freifunk/root/usr/share/rpcd/acl.d/luci-mod-freifunk.json:8]: Wow, "profile (Expert)" - I always thought this is read-only ... So write-permission are required.

Even I'm not sure if it's a great idea to edit a community profile, but that's another issue.

**Comment by SvenRoederer** [comment]
Can you please also add a SoB message as DCO.

**Comment by SvenRoederer** [comment]
merged in 98e83ff and thanks for checking the DCO-GitHub-Action
